[package]
name = "pcrt-recorder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["license", "opencv-source"]
license = ["dep:pcrt-license"]
opencv-source = ["pcrt-recording/opencv-source"]

[[bin]]
name = "pcrt-recorder"
path = "src/main.rs"
required-features = ["opencv-source"]

[dependencies]
pcrt-recording = { path = "../../crates/pcrt-recording" }
pcrt-door-zmq = { path = "../../crates/pcrt-door-zmq" }
pcrt-license = { path = "../../crates/pcrt-license", optional = true }
pcrt-service = { path = "../../crates/pcrt-service" }
pcrt-storage = { path = "../../crates/pcrt-storage" }
ctrlc = "3.5.2"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
