[package]
name = "pcrt-processor"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ctrlc = "3.5.2"
fs2 = "0.4.3"
pcrt-door-zmq = { path = "../../crates/pcrt-door-zmq" }
pcrt-processing = { path = "../../crates/pcrt-processing" }
pcrt-result-queue = { path = "../../crates/pcrt-result-queue" }
pcrt-service = { path = "../../crates/pcrt-service" }
pcrt-storage = { path = "../../crates/pcrt-storage" }

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
