[package]
name = "pcrt-processor"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["license"]
license = ["dep:pcrt-license"]

[dependencies]
chrono = "0.4.42"
ctrlc = "3.5.2"
fs2 = "0.4.3"
opencv = { version = "0.100.1", default-features = false, features = ["imgproc", "videoio"] }
openvino = { version = "0.11.0", features = ["runtime-linking"] }
pcrt-door-zmq = { path = "../../crates/pcrt-door-zmq" }
pcrt-license = { path = "../../crates/pcrt-license", optional = true }
pcrt-model = { path = "../../crates/pcrt-model" }
pcrt-processing = { path = "../../crates/pcrt-processing" }
pcrt-result-queue = { path = "../../crates/pcrt-result-queue" }
pcrt-service = { path = "../../crates/pcrt-service" }
pcrt-storage = { path = "../../crates/pcrt-storage" }
serde_json = "1.0.149"
trackforge = "0.3.0"

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
