[package]
name = "pcrt-recording"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
opencv-source = ["dep:opencv"]

[dependencies]
opencv = { version = "0.98", default-features = false, features = ["imgproc", "videoio"], optional = true }
pcrt-storage = { path = "../pcrt-storage" }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
