[package]
name = "pcrt-result-queue"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pcrt-model = { path = "../pcrt-model" }
rusqlite = { version = "0.37.0", features = ["bundled"] }

[lints]
workspace = true
