[package]
name = "pcrt-license-tool"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pcrt-license = { path = "../../crates/pcrt-license" }
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde_json = "1.0.149"

[lints]
workspace = true
